## Media Monitoring Using Sentiment Analysis

In [6]:
#BASIC LIBRARIES
import pandas as pd 
import numpy as np   

import matplotlib.pyplot as plt 
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [10]:
#Importing the dataset
tweets = pd.read_csv('tweets.csv')
tweets.head()

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [12]:
# Defining a function to remove stop words, urls and symbols etc.

import nltk
import re, string
from bs4 import BeautifulSoup
from string import punctuation
import nltk
# nltk.download('punkt')
from nltk.tokenize import punkt
from nltk.tokenize import word_tokenize
from nltk import sent_tokenize
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer


def gettext(message):
    text = BeautifulSoup(message, 'html.parser')
    return text.get_text()

def removehurls(message):
    return re.sub(r'http\S+', '', message)

def removesymbols(message):
    re.sub(r'^\x00-\x7F+', '', message)
    return re.sub('[@!.,\/&)?:#...-'']', '', message)

def removestopwords(message):
    new_message = []
    message = message.lower()
    message = word_tokenize(message)
    sw = stopwords.words('english')
    for msg in message:
        if msg not in sw:
            new_message.append(msg) 
    return ' '.join(new_message)

def preparemessage(message):
    message = gettext(message)
    message = removehurls(message)
    message = removesymbols(message)
    message = removestopwords(message)
    return message

In [18]:
tweets['messagenew'] = tweets['text'].apply(preparemessage)

In [19]:
tweets.head()

,target,id,date,flag,user,text,messagenew
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",switchfoot awww 's bummer shoulda got david ca...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,upset ca n't update facebook texting might cry...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,kenichan dived many times ball managed save 50...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole body feels itchy like fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",nationwideclass 's behaving 'm mad ca n't see